"""auto migration 20250731025108

Revision ID: 2e69b5d5a3d4
Revises: f734bec9756c
Create Date: 2025-07-31 02:51:10.268072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e69b5d5a3d4'
down_revision: Union[str, Sequence[str], None] = 'f734bec9756c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
