"""auto migration 20250731151452

Revision ID: 4a51dcbfe8fd
Revises: 68bb4f96af3c
Create Date: 2025-07-31 15:14:55.540098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a51dcbfe8fd'
down_revision: Union[str, Sequence[str], None] = '68bb4f96af3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
