"""auto migration 20250731130527

Revision ID: 60c12b9f9ad3
Revises: ffc63250741d
Create Date: 2025-07-31 13:05:30.448010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60c12b9f9ad3'
down_revision: Union[str, Sequence[str], None] = 'ffc63250741d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
