"""auto migration 20250730055201

Revision ID: 75bbc7eb971c
Revises: bdeb98a75540
Create Date: 2025-07-30 05:52:03.067300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75bbc7eb971c'
down_revision: Union[str, Sequence[str], None] = 'bdeb98a75540'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
