"""auto migration 20250804064335

Revision ID: 960df25b2f86
Revises: d1aaf1f0659f
Create Date: 2025-08-04 06:43:37.318080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '960df25b2f86'
down_revision: Union[str, Sequence[str], None] = 'd1aaf1f0659f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
