"""auto migration 20250801040558

Revision ID: a464a4f89b0d
Revises: abe6e8ab8a20
Create Date: 2025-08-01 04:06:01.891652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a464a4f89b0d'
down_revision: Union[str, Sequence[str], None] = 'abe6e8ab8a20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
