"""auto migration 20250801071705

Revision ID: bb3c436b3d6d
Revises: 73c03d1e7ebd
Create Date: 2025-08-01 07:17:07.288693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb3c436b3d6d'
down_revision: Union[str, Sequence[str], None] = '73c03d1e7ebd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
