"""auto migration 20250731131205

Revision ID: caf1ffc87eb7
Revises: 60c12b9f9ad3
Create Date: 2025-07-31 13:12:09.030235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'caf1ffc87eb7'
down_revision: Union[str, Sequence[str], None] = '60c12b9f9ad3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
