"""auto migration 20250730053652

Revision ID: cc4ed1ce0f6c
Revises: 774ee44cbbbc
Create Date: 2025-07-30 05:36:53.495934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc4ed1ce0f6c'
down_revision: Union[str, Sequence[str], None] = '774ee44cbbbc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
