"""auto migration 20250730053844

Revision ID: ccc889bea4b1
Revises: cc4ed1ce0f6c
Create Date: 2025-07-30 05:38:45.394385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ccc889bea4b1'
down_revision: Union[str, Sequence[str], None] = 'cc4ed1ce0f6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
