"""auto migration 20250731030455

Revision ID: d39f22f46f1e
Revises: 2e69b5d5a3d4
Create Date: 2025-07-31 03:04:57.309363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd39f22f46f1e'
down_revision: Union[str, Sequence[str], None] = '2e69b5d5a3d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
