"""auto migration 20250729150635

Revision ID: d43cc0a68af8
Revises: 63a8ecc0cc8d
Create Date: 2025-07-29 15:06:37.034920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd43cc0a68af8'
down_revision: Union[str, Sequence[str], None] = '63a8ecc0cc8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
