"""auto migration 20250731140023

Revision ID: f56de5c75d0d
Revises: 3a6b6ed66a74
Create Date: 2025-07-31 14:00:26.414354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f56de5c75d0d'
down_revision: Union[str, Sequence[str], None] = '3a6b6ed66a74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
